### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by Naren5743** [trekkspace/dbd-skillcheck-simulator#11]
Go in http://dbd.trekkspace.com/ 

Got:
This site can’t be reachedCheck if there is a typo in dbd.trekkspace.com.
If spelling is correct, try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by lucafont2** [comment]
Check out my fork. I'm trying to update the code adding the new perks and skillchecks
https://github.com/lucafont2/dbd-skillcheck-simulator

**Comment by trekkspace** [comment]
> Check out my fork. I'm trying to update the code adding the new perks and skillchecks https://github.com/lucafont2/dbd-skillcheck-simulator

Thank you for your interest in this project, well the code wasn't been maintained lately, so it would be great to update it, if you run through any problems with the code or have any questions feel free to reach me. Thank you.

**Comment by trekkspace** [comment]
> Go in http://dbd.trekkspace.com/
> 
> Got: This site can’t be reachedCheck if there is a typo in dbd.trekkspace.com. If spelling is correct, try running Windows Network Diagnostics. DNS_PROBE_FINISHED_NXDOMAIN

Hosted by Github, the site will always be working if the domain is still active.

**Comment by lucafont2** [comment]
> > Check out my fork. I'm trying to update the code adding the new perks and skillchecks https://github.com/lucafont2/dbd-skillcheck-simulator
> 
> Thank you for your interest in this project, well the code wasn't been maintained lately, so it would be great to update it, if you run through any problems with the code or have any questions feel free to reach me. Thank you.

I have to thank you for the code. I already changed things to keep up the new versions of dbd. If in the future you want to merge some of my codes and you have any questions you can reach me on telegram @lucazio22 ( I think your discord user is outdated )
